### Import Libraries

In [1]:

import numpy as np
import pandas as pd
import glob
import time
import pandas as pd
# from xml.dom import minidom


import os
import matplotlib.pyplot as plt
import keras

import cv2

Using TensorFlow backend.

In [2]:
df=pd.read_csv('/kaggle/input/cross-site-scripting-xss-dataset-for-deep-learning/XSS_dataset.csv', encoding='utf-8-sig')

In [3]:
df.head()

   Unnamed: 0                                           Sentence  Label
0           0  <li><a href="/wiki/File:Socrates.png" class="i...      0
1           1               <tt onmouseover="alert(1)">test</tt>      1
2           2  \t </span> <span class="reference-text">Steeri...      0
3           3  \t </span> <span class="reference-text"><cite ...      0
4           4  \t </span>. <a href="/wiki/Digital_object_iden...      0

In [4]:
df=df[df.columns[-2:]]  # Only get sentence and labels

In [5]:
df.head()

                                            Sentence  Label
0  <li><a href="/wiki/File:Socrates.png" class="i...      0
1               <tt onmouseover="alert(1)">test</tt>      1
2  \t </span> <span class="reference-text">Steeri...      0
3  \t </span> <span class="reference-text"><cite ...      0
4  \t </span>. <a href="/wiki/Digital_object_iden...      0

In [6]:
# Get Sentences data from data frame
sentences=df['Sentence'].values
sentences[1]

'<tt onmouseover="alert(1)">test</tt>'

In [7]:
print(len(sentences))

13686

In [8]:
# Convert to ASCII

def convert_to_ascii(sentence):
    sentence_ascii=[]

    for i in sentence:
        
        
        """Some characters have values very big e.d 8221 adn some are chinese letters
        I am removing letters having values greater than 8222 and for rest greater 
        than 128 and smaller than 8222 assigning them values so they can easily be normalized"""
       
        if(ord(i)<8222):      # ” has ASCII of 8221
            
            if(ord(i)==8217): # ’  :  8217
                sentence_ascii.append(134)
            
            
            if(ord(i)==8221): # ”  :  8221
                sentence_ascii.append(129)
                
            if(ord(i)==8220): # “  :  8220
                sentence_ascii.append(130)
                
                
            if(ord(i)==8216): # ‘  :  8216
                sentence_ascii.append(131)
                
            if(ord(i)==8217): # ’  :  8217
                sentence_ascii.append(132)
            
            if(ord(i)==8211): # –  :  8211
                sentence_ascii.append(133)
                
                
            """
            If values less than 128 store them else discard them
            """
            if (ord(i)<=128):
                    sentence_ascii.append(ord(i))
    
            else:
                    pass
            

    zer=np.zeros((10000))

    for i in range(len(sentence_ascii)):
        zer[i]=sentence_ascii[i]

    zer.shape=(100, 100)


#     plt.plot(image)
#     plt.show()
    return zer

In [9]:


# send each sentence to be converted to ASCII


arr=np.zeros((len(sentences),100,100))

for i in range(len(sentences)):
    
    image=convert_to_ascii(sentences[i])

    x=np.asarray(image,dtype='float')
    image =  cv2.resize(x, dsize=(100,100), interpolation=cv2.INTER_CUBIC)
    image/=128

    
#     if i==1:
#         plt.plot(image)
#         plt.show()    
    arr[i]=image

In [10]:
print("Input data shape : ", arr.shape)

Input data shape :  (13686, 100, 100)

In [11]:
# Reshape data for input to CNN
data = arr.reshape(arr.shape[0], 100, 100, 1)

In [12]:
data.shape

(13686, 100, 100, 1)

In [13]:
y=df['Label'].values

In [14]:
# Split into train/test data
from sklearn.model_selection import train_test_split
trainX, testX, trainY, testY = train_test_split(data,y, test_size=0.2, random_state=42)

In [15]:
# import libraries for Making Model
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense, Activation, Conv2D, MaxPooling2D,Flatten,Dropout,MaxPool2D, BatchNormalization

In [16]:
# A basic CNN Model
# Number of layers = 11
# Number of Convolutional layer: 3

model=tf.keras.models.Sequential([
    
    tf.keras.layers.Conv2D(64,(3,3), activation=tf.nn.relu, input_shape=(100,100,1)),
    tf.keras.layers.MaxPooling2D(2,2),
    
    tf.keras.layers.Conv2D(128,(3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2,2),
    
    tf.keras.layers.Conv2D(256,(3,3), activation='relu'),
    tf.keras.layers.MaxPooling2D(2,2),
    
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(256, activation='relu'),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
    
])

In [17]:

model.compile(loss='binary_crossentropy', 
              optimizer='adam', 
              metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
conv2d (Conv2D)              (None, 98, 98, 64)        640
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 49, 49, 64)        0
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 47, 47, 128)       73856
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 23, 23, 128)       0
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 21, 21, 256)       295168
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 10, 10, 256)       0
_________________________________________________________________
flatten (Flatten)            (None, 25600)             0
_________________________________________________________________
dense (Dense)                (None, 256)               6553856
_________________________________________________________________
dense_1 (Dense)              (None, 128)               32896
_________________________________________________________________
dense_2 (Dense)              (None, 64)                8256
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 65
=================================================================
Total params: 6,964,737
Trainable params: 6,964,737
Non-trainable params: 0
_________________________________________________________________

In [18]:
# Stop when validation accuracy > 97

class myCallback(tf.keras.callbacks.Callback):
    def on_epoch_end(self, epoch, logs={}):
        if(logs.get('val_accuracy')>0.97):
            print(" \n Reached 97% + validation accuracy")
            self.model.stop_training=True
callbacks = myCallback()

In [19]:
batch_size = 128
num_epoch = 10
#model training
model_log = model.fit(trainX, trainY,
          batch_size=batch_size,
          epochs=num_epoch,
          verbose=1,
          validation_data=( testX,  testY)
#                        callbacks=[callbacks]
                     )

Train on 10948 samples, validate on 2738 samples
Epoch 1/10
10948/10948 [==============================] - 233s 21ms/sample - loss: 0.4375 - accuracy: 0.7922 - val_loss: 0.3675 - val_accuracy: 0.8495
Epoch 2/10
10948/10948 [==============================] - 232s 21ms/sample - loss: 0.1556 - accuracy: 0.9425 - val_loss: 0.1234 - val_accuracy: 0.9580
Epoch 3/10
10948/10948 [==============================] - 232s 21ms/sample - loss: 0.0709 - accuracy: 0.9790 - val_loss: 0.0631 - val_accuracy: 0.9788
Epoch 4/10
10948/10948 [==============================] - 231s 21ms/sample - loss: 0.0513 - accuracy: 0.9857 - val_loss: 0.0567 - val_accuracy: 0.9836
Epoch 5/10
10948/10948 [==============================] - 233s 21ms/sample - loss: 0.0471 - accuracy: 0.9862 - val_loss: 0.0525 - val_accuracy: 0.9865
Epoch 6/10
10948/10948 [==============================] - 232s 21ms/sample - loss: 0.0412 - accuracy: 0.9877 - val_loss: 0.0510 - val_accuracy: 0.9843
Epoch 7/10
10948/10948 [==============================] - 233s 21ms/sample - loss: 0.0352 - accuracy: 0.9895 - val_loss: 0.0732 - val_accuracy: 0.9828
Epoch 8/10
10948/10948 [==============================] - 235s 21ms/sample - loss: 0.0315 - accuracy: 0.9904 - val_loss: 0.0423 - val_accuracy: 0.9883
Epoch 9/10
10948/10948 [==============================] - 235s 21ms/sample - loss: 0.0231 - accuracy: 0.9930 - val_loss: 0.0531 - val_accuracy: 0.9847
Epoch 10/10
10948/10948 [==============================] - 234s 21ms/sample - loss: 0.0361 - accuracy: 0.9879 - val_loss: 0.0647 - val_accuracy: 0.9795

In [20]:
# predict for test set
pred=model.predict(testX)

In [21]:
# Threshold values predicted

for i in range(len(pred)):
    if pred[i]>0.5:
        pred[i]=1
    elif pred[i]<=0.5:
        pred[i]=0

In [22]:
# Count True predicted and wrong predicted

true=0
false=0

for i in range(len(pred)):
    if pred[i] == testY[i]:
        true+=1
    else:
        false+=1
        
print("correct predicted :: ", true)
print("false prediction :: ", false)

correct predicted ::  2682
false prediction ::  56

In [23]:
# Number of attack and benign data in test set

attack=0
benign=0
for i in range(len(testY)):
    if testY[i]==1:
        attack+=1
    else:
        benign+=1

print("Attack data in test set :: ", attack)
print(" Benign data in test set :: ", benign)

Attack data in test set ::  1478
 Benign data in test set ::  1260

### Confusion Matrix

In [24]:
# Takes True positive, true negative, false positive and false negative as input
# Returns Accuracy

def accuracy_function(tp,tn,fp,fn):
    
    accuracy = (tp+tn) / (tp+tn+fp+fn)
    
    return accuracy

In [25]:
# Takes True Positive and false positive
# Returns Precision

def precision_function(tp,fp):
    
    precision = tp / (tp+fp)
    
    return precision

In [26]:
#Takes True Positive and false negative
# Returns Recall

def recall_function(tp,fn):
    
    recall=tp / (tp+fn)
    
    return recall

In [27]:
#Takes true values and predicted
# Returns Accuracy, precision and recall


def confusion_matrix(truth,predicted):
    
    true_positive = 0
    true_negative = 0
    false_positive = 0
    false_negative = 0
    
    for true,pred in zip(truth,predicted):
        if true == 1:
            if pred == true:
                true_positive += 1
            elif pred != true:
                false_negative += 1

        elif true == 0:
            if pred == true:
                true_negative += 1
            elif pred != true:
                false_positive += 1
            
    accuracy=accuracy_function(true_positive, true_negative, false_positive, false_negative)
    precision=precision_function(true_positive, false_positive)
    recall=recall_function(true_positive, false_negative)
    
    return (accuracy,
            precision,
           recall)

In [28]:
accuracy,precision,recall=confusion_matrix(testY,pred)

In [29]:
print(" Accuracy : {0} \n Precision : {1} \n Recall : {2}".format(accuracy, precision, recall))

 Accuracy : 0.9795471146822499
 Precision : 0.9930651872399445
 Recall : 0.9688768606224628

In [ ]:
from flask import Flask, request, jsonify, render_template
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import load_model
import cv2
import warnings
warnings.filterwarnings("ignore", category=UserWarning, module='IPython.core.interactiveshell')

app = Flask(__name__)

# Load the trained model
model = load_model('xss_model.h5')

# Function to preprocess input
def preprocess_input(sentence):
    sentence_ascii = []
    for char in sentence:
        if ord(char) < 8222:
            if ord(char) == 8217:  # Special case for ’
                sentence_ascii.append(134)
            elif ord(char) == 8221:  # Special case for ”
                sentence_ascii.append(129)
            elif ord(char) == 8220:  # Special case for “
                sentence_ascii.append(130)
            elif ord(char) == 8216:  # Special case for ‘
                sentence_ascii.append(131)
            elif ord(char) == 8211:  # Special case for –
                sentence_ascii.append(133)
            elif ord(char) <= 128:
                sentence_ascii.append(ord(char))

    zer = np.zeros((10000))
    for i in range(len(sentence_ascii)):
        zer[i] = sentence_ascii[i]

    zer = zer.reshape((100, 100))
    image = cv2.resize(zer, (100, 100), interpolation=cv2.INTER_CUBIC)
    image = image / 128  # Normalize
    return image.reshape(1, 100, 100, 1)

@app.route('/')
def home():
    return render_template('index.html')

@app.route('/predict', methods=['POST'])
def predict():
    # Get user input
    input_text = request.form.get('sentence')
    if not input_text:
        return jsonify({"error": "Please provide a valid input"}), 400

    # Preprocess input
    processed_input = preprocess_input(input_text)

    # Make prediction
    prediction = model.predict(processed_input)
    prediction_class = 1 if prediction[0][0] > 0.5 else 0

    # Return result
    result = {
        "input": input_text,
        "prediction": "Attack Detected" if prediction_class == 1 else "Benign",
        "confidence": float(prediction[0][0])
    }
    return jsonify(result)
if __name__ == '__main__':
    app.run(debug=True, port=5001, host='0.0.0.0', use_reloader=False)